### ISSUE TITLE
Formato de arquivo

### ISSUE THREAD

**Issue by LucasFernandesBrazil** [AlexG21-co/Projeto-de-Agencia#1]
Olá Alex!

Você subiu seu projeto em formato .rar, sendo de difícil visualização no GitHub.

Para melhorar a navegabilidade sua e de outros colaboradores suba o arquivo sem comprimir.

Atenciosamente,
Lucas Fernandes :)

**Comment by AlexG21-co** [comment]
Obrigado pelo aviso

Em qui, 15 de jul de 2021 8:18 PM, Lucas Fernandes ***@***.***>
escreveu:

**Comment by LucasFernandesBrazil** [comment]
É um prazer ajudar!
